services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules # explicitly specifying to use the node_modules build inside container
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/messdb

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # explicitly specifying to use the node_modules build inside container
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
