const YEAR_IN_MILLI_SECONDS = 31536000000
const MINUTES_IN_SECONDS = 60
const MINUTES_IN_MILLISECOND = MINUTES_IN_SECONDS * 1000

const HOUR_IN_MINUTES = 60
const HOUR_IN_SECONDS = HOUR_IN_MINUTES * MINUTES_IN_SECONDS
const HOUR_IN_MILLISECONDS = HOUR_IN_SECONDS * 1000

const DAY_IN_HOUR = 24
const DAY_IN_MINUTES = DAY_IN_HOUR * HOUR_IN_MINUTES
const DAY_IN_SECONDS = DAY_IN_MINUTES * MINUTES_IN_SECONDS
const DAY_IN_MILLISECONDS = DAY_IN_SECONDS * 1000

const MONTH_IN_DAYS = 30
const MONTH_IN_MILLISECONDS = MONTH_IN_DAYS * DAY_IN_MILLISECONDS

export const ACCESS_TOKEN_EXPIRE_TIME = 15 * MINUTES_IN_MILLISECOND
export const REFRESH_TOKEN_EXPIRE_TIME = HOUR_IN_MILLISECONDS
